export const nouns = [
  // originais
  { word: "lua", themes: ["noite", "romantico", "silencio"] },
  { word: "sol", themes: ["dia", "esperanca", "natureza"] },
  { word: "vento", themes: ["natureza", "liberdade", "melancolico"] },
  { word: "chuva", themes: ["chuva", "triste", "romantico"] },
  { word: "mar", themes: ["mar", "natureza", "profundo"] },
  { word: "rio", themes: ["natureza", "tempo"] },
  { word: "céu", themes: ["natureza", "dia", "noite"] },
  { word: "estrela", themes: ["noite", "esperanca", "romantico"] },
  { word: "nuvem", themes: ["natureza", "dia", "leve"] },
  { word: "sombra", themes: ["silencio", "melancolico"] },
  { word: "silêncio", themes: ["silencio", "intimista"] },
  { word: "eco", themes: ["silencio", "memoria"] },
  { word: "tempo", themes: ["tempo", "filosofico"] },
  { word: "instante", themes: ["tempo", "intimista"] },
  { word: "lembrança", themes: ["memoria", "romantico"] },
  { word: "saudade", themes: ["romantico", "triste", "melancolico"] },
  { word: "coração", themes: ["romantico", "intimista"] },
  { word: "olhar", themes: ["romantico", "intimista"] },
  { word: "toque", themes: ["romantico", "intimista"] },
  { word: "voz", themes: ["intimista", "memoria"] },
  { word: "noite", themes: ["noite", "melancolico"] },
  { word: "tarde", themes: ["tempo", "melancolico"] },
  { word: "manhã", themes: ["dia", "esperanca"] },
  { word: "janela", themes: ["cotidiano", "intimista"] },
  { word: "porta", themes: ["cotidiano", "simbolico"] },
  { word: "café", themes: ["cotidiano", "intimista", "romantico"] },
  { word: "mesa", themes: ["cotidiano"] },
  { word: "rua", themes: ["cotidiano", "solidao"] },
  { word: "passo", themes: ["tempo", "movimento"] },
  { word: "caminho", themes: ["tempo", "filosofico"] },

  // novos – expandidos
  { word: "orvalho", themes: ["manha", "leve", "natureza"] },
  { word: "névoa", themes: ["manha", "silencio", "mistério"] },
  { word: "montanha", themes: ["natureza", "profundo", "solidao"] },
  { word: "floresta", themes: ["natureza", "silencio", "mistério"] },
  { word: "folha", themes: ["natureza", "leve", "tempo"] },
  { word: "flor", themes: ["natureza", "romantico", "leve"] },
  { word: "pedra", themes: ["natureza", "tempo", "eterno"] },
  { word: "areia", themes: ["mar", "tempo", "leve"] },
  { word: "onda", themes: ["mar", "movimento", "tempo"] },
  { word: "espuma", themes: ["mar", "leve", "instante"] },
  { word: "horizonte", themes: ["mar", "dia", "filosofico"] },
  { word: "luz", themes: ["dia", "esperanca", "intimista"] },
  { word: "sombra", themes: ["noite", "melancolico", "silencio"] },
  { word: "crepúsculo", themes: ["dia", "noite", "melancolico"] },
  { word: "aurora", themes: ["dia", "esperanca", "natureza"] },
  { word: "bruma", themes: ["manha", "mistério", "leve"] },
  { word: "garoa", themes: ["chuva", "leve", "intimista"] },
  { word: "trovão", themes: ["chuva", "natureza", "forte"] },
  { word: "relâmpago", themes: ["chuva", "instante", "intenso"] },
  { word: "brisa", themes: ["natureza", "leve", "liberdade"] },
  { word: "furacão", themes: ["natureza", "intenso", "caos"] },
  { word: "neve", themes: ["natureza", "silencio", "frio"] },
  { word: "gelo", themes: ["frio", "silencio", "tempo"] },
  { word: "fogo", themes: ["intenso", "paixao", "transformação"] },
  { word: "chama", themes: ["intenso", "paixao", "esperanca"] },
  { word: "cinza", themes: ["tempo", "melancolico", "memoria"] },
  { word: "pó", themes: ["tempo", "memoria", "leve"] },
  { word: "poeira", themes: ["cotidiano", "tempo", "leve"] },
  { word: "espelho", themes: ["intimista", "identidade", "memoria"] },
  { word: "retrato", themes: ["memoria", "tempo", "intimista"] },
  { word: "carta", themes: ["memoria", "romantico", "distancia"] },
  { word: "livro", themes: ["intimista", "tempo", "memoria"] },
  { word: "poema", themes: ["intimista", "romantico", "arte"] },
  { word: "canção", themes: ["intimista", "romantico", "memoria"] },
  { word: "lágrima", themes: ["triste", "romantico", "leve"] },
  { word: "sorriso", themes: ["alegria", "romantico", "leve"] },
  { word: "beijo", themes: ["romantico", "intimista", "instante"] },
  { word: "abraço", themes: ["romantico", "intimista", "aconchego"] },
  { word: "mão", themes: ["intimista", "toque", "memoria"] },
  { word: "dedo", themes: ["intimista", "toque", "leve"] },
  { word: "pele", themes: ["intimista", "toque", "sensação"] },
  { word: "cabelo", themes: ["intimista", "leve", "tempo"] },
  { word: "rosto", themes: ["intimista", "identidade", "tempo"] },
  { word: "olhos", themes: ["intimista", "romantico", "profundo"] },
  { word: "boca", themes: ["intimista", "romantico", "expressão"] },
  { word: "sombrancelha", themes: ["intimista", "expressão"] },
  { word: "pálpebra", themes: ["intimista", "silencio", "sonho"] },
  { word: "sonho", themes: ["noite", "esperanca", "intimista"] },
  { word: "pesadelo", themes: ["noite", "triste", "medo"] },
  { word: "memória", themes: ["memoria", "tempo", "intimista"] },
  { word: "esquecimento", themes: ["memoria", "tempo", "triste"] },
  { word: "ausência", themes: ["triste", "melancolico", "solidao"] },
  { word: "presença", themes: ["intimista", "aconchego", "romantico"] },
  { word: "distância", themes: ["romantico", "melancolico", "tempo"] },
  { word: "encontro", themes: ["romantico", "tempo", "destino"] },
  { word: "despedida", themes: ["triste", "tempo", "melancolico"] },
  { word: "espera", themes: ["tempo", "romantico", "intimista"] },
  { word: "fim", themes: ["tempo", "melancolico", "filosofico"] },
  { word: "começo", themes: ["tempo", "esperanca", "renovação"] },
  { word: "recomeço", themes: ["esperanca", "tempo", "renovação"] },
  { word: "viagem", themes: ["tempo", "movimento", "filosofico"] },
  { word: "partida", themes: ["tempo", "movimento", "melancolico"] },
  { word: "chegada", themes: ["tempo", "esperanca", "aconchego"] },
  { word: "cais", themes: ["mar", "despedida", "espera"] },
  { word: "ponte", themes: ["conexão", "tempo", "simbolico"] },
  { word: "beco", themes: ["cotidiano", "solidao", "mistério"] },
  { word: "praça", themes: ["cotidiano", "encontro", "movimento"] },
  { word: "jardim", themes: ["natureza", "intimista", "paz"] },
  { word: "quintal", themes: ["cotidiano", "memoria", "aconchego"] },
  { word: "telhado", themes: ["cotidiano", "chuva", "observação"] },
  { word: "varanda", themes: ["cotidiano", "intimista", "observação"] },
  { word: "escada", themes: ["tempo", "movimento", "simbolico"] },
  { word: "corredor", themes: ["cotidiano", "tempo", "memoria"] },
  { word: "quarto", themes: ["intimista", "silencio", "sonho"] },
  { word: "cama", themes: ["intimista", "sonho", "aconchego"] },
  { word: "almofada", themes: ["intimista", "aconchego", "leve"] },
  { word: "cobertor", themes: ["intimista", "frio", "aconchego"] },
  { word: "xícara", themes: ["cotidiano", "intimista", "aconchego"] },
  { word: "pão", themes: ["cotidiano", "simples", "aconchego"] },
  { word: "vinho", themes: ["romantico", "intimista", "celebração"] },
  { word: "fruta", themes: ["natureza", "simples", "leve"] },
  { word: "maçã", themes: ["natureza", "simbolico", "simples"] },
  { word: "laranja", themes: ["natureza", "cor", "leve"] },
  { word: "mel", themes: ["natureza", "doce", "leve"] },
  { word: "sal", themes: ["mar", "simbolico", "tempo"] },
  { word: "água", themes: ["natureza", "vida", "leve"] },
  { word: "fonte", themes: ["natureza", "vida", "movimento"] },
  { word: "poço", themes: ["natureza", "profundo", "mistério"] },
  { word: "lago", themes: ["natureza", "silencio", "profundo"] },
  { word: "lagoa", themes: ["natureza", "silencio", "intimista"] },
  { word: "cachoeira", themes: ["natureza", "movimento", "força"] },
  { word: "rocha", themes: ["natureza", "tempo", "eterno"] },
  { word: "caverna", themes: ["natureza", "mistério", "silencio"] },
  { word: "ilha", themes: ["mar", "solidao", "intimista"] },
  { word: "deserto", themes: ["natureza", "solidao", "tempo"] },
  { word: "oásis", themes: ["natureza", "esperanca", "vida"] },
  { word: "estrada", themes: ["tempo", "movimento", "filosofico"] },
  { word: "trilha", themes: ["natureza", "movimento", "descoberta"] },
  { word: "encruzilhada", themes: ["tempo", "escolha", "destino"] },
  { word: "ponto", themes: ["simbolico", "tempo", "intimista"] },
  { word: "ciclo", themes: ["tempo", "natureza", "filosofico"] },
  { word: "ritmo", themes: ["tempo", "movimento", "natureza"] },
  { word: "pausa", themes: ["tempo", "silencio", "intimista"] },
  { word: "vazio", themes: ["solidao", "filosofico", "silencio"] },
  { word: "plenitude", themes: ["intimista", "paz", "aconchego"] },
  { word: "caos", themes: ["intenso", "movimento", "filosofico"] },
  { word: "ordem", themes: ["calma", "filosofico", "natureza"] },
  { word: "mistério", themes: ["noite", "filosofico", "intimista"] },
  { word: "segredo", themes: ["intimista", "silencio", "mistério"] },
  { word: "verdade", themes: ["filosofico", "intimista", "claro"] },
  { word: "mentira", themes: ["melancolico", "intimista", "triste"] }
]

export const verbs = [
  // originais
  { word: "cai", themes: ["chuva", "tempo", "triste"] },
  { word: "escorre", themes: ["chuva", "tempo"] },
  { word: "passa", themes: ["tempo", "cotidiano"] },
  { word: "flutua", themes: ["leve", "natureza"] },
  { word: "brilha", themes: ["noite", "dia", "esperanca"] },
  { word: "some", themes: ["silencio", "triste"] },
  { word: "surge", themes: ["dia", "esperanca"] },
  { word: "nasce", themes: ["dia", "esperanca"] },
  { word: "morre", themes: ["triste", "melancolico"] },
  { word: "renasce", themes: ["esperanca", "tempo"] },
  { word: "dança", themes: ["natureza", "leve"] },
  { word: "sopra", themes: ["natureza", "vento"] },
  { word: "corre", themes: ["tempo", "natureza"] },
  { word: "desaparece", themes: ["silencio", "tempo"] },
  { word: "permanece", themes: ["tempo", "intimista"] },
  { word: "espera", themes: ["romantico", "tempo"] },
  { word: "lembra", themes: ["memoria", "romantico"] },
  { word: "esquece", themes: ["memoria", "triste"] },
  { word: "retorna", themes: ["memoria", "tempo"] },
  { word: "observa", themes: ["intimista"] },
  { word: "sente", themes: ["intimista", "romantico"] },
  { word: "chama", themes: ["romantico"] },
  { word: "guarda", themes: ["memoria", "intimista"] },
  { word: "toca", themes: ["romantico", "intimista"] },
  { word: "eco(a)", themes: ["silencio", "memoria"] },
  { word: "silencia", themes: ["silencio"] },
  { word: "desliza", themes: ["leve", "natureza"] },
  { word: "envolve", themes: ["intimista", "romantico"] },

  // novos – expandidos
  { word: "amanhece", themes: ["dia", "esperanca", "renovação"] },
  { word: "entardece", themes: ["tempo", "melancolico", "dia"] },
  { word: "anoitece", themes: ["noite", "silencio", "tempo"] },
  { word: "cinge", themes: ["noite", "intimista", "envolver"] },
  { word: "desperta", themes: ["manha", "esperanca", "vida"] },
  { word: "adormece", themes: ["noite", "silencio", "sonho"] },
  { word: "respira", themes: ["vida", "calma", "intimista"] },
  { word: "suspiro", themes: ["intimista", "melancolico", "leve"] },
  { word: "chora", themes: ["triste", "chuva", "intimista"] },
  { word: "ri", themes: ["alegria", "leve", "romantico"] },
  { word: "sussurra", themes: ["silencio", "intimista", "vento"] },
  { word: "grita", themes: ["intenso", "natureza", "paixao"] },
  { word: "canta", themes: ["alegria", "natureza", "intimista"] },
  { word: "cala", themes: ["silencio", "intimista", "triste"] },
  { word: "abre", themes: ["esperanca", "dia", "descoberta"] },
  { word: "fecha", themes: ["noite", "silencio", "melancolico"] },
  { word: "entra", themes: ["intimista", "cotidiano", "aconchego"] },
  { word: "sai", themes: ["movimento", "despedida", "cotidiano"] },
  { word: "sobe", themes: ["movimento", "esperanca", "céu"] },
  { word: "desce", themes: ["movimento", "terra", "melancolico"] },
  { word: "voa", themes: ["leve", "liberdade", "natureza"] },
  { word: "pousa", themes: ["leve", "natureza", "calma"] },
  { word: "mergulha", themes: ["mar", "profundo", "intimista"] },
  { word: "navega", themes: ["mar", "tempo", "filosofico"] },
  { word: "erra", themes: ["caminho", "tempo", "filosofico"] },
  { word: "acerta", themes: ["destino", "tempo", "encontro"] },
  { word: "encontra", themes: ["destino", "romantico", "tempo"] },
  { word: "perde", themes: ["tempo", "triste", "memoria"] },
  { word: "ganha", themes: ["esperanca", "renovação", "leve"] },
  { word: "transforma", themes: ["tempo", "natureza", "filosofico"] },
  { word: "muda", themes: ["tempo", "renovação", "cotidiano"] },
  { word: "cresce", themes: ["natureza", "tempo", "esperanca"] },
  { word: "floresce", themes: ["natureza", "esperanca", "beleza"] },
  { word: "murcha", themes: ["natureza", "tempo", "triste"] },
  { word: "seca", themes: ["natureza", "tempo", "triste"] },
  { word: "molha", themes: ["chuva", "natureza", "leve"] },
  { word: "inunda", themes: ["chuva", "intenso", "emoção"] },
  { word: "queima", themes: ["fogo", "intenso", "paixao"] },
  { word: "congela", themes: ["frio", "tempo", "silencio"] },
  { word: "derrete", themes: ["fogo", "tempo", "transformação"] },
  { word: "quebra", themes: ["intenso", "triste", "transformação"] },
  { word: "parte", themes: ["despedida", "tempo", "movimento"] },
  { word: "junta", themes: ["encontro", "romantico", "uniao"] },
  { word: "segue", themes: ["caminho", "tempo", "destino"] },
  { word: "volta", themes: ["memoria", "tempo", "recomeço"] },
  { word: "foge", themes: ["medo", "tempo", "movimento"] },
  { word: "persiste", themes: ["tempo", "esperanca", "força"] },
  { word: "resiste", themes: ["força", "tempo", "natureza"] },
  { word: "aceita", themes: ["tempo", "intimista", "filosofico"] },
  { word: "nega", themes: ["intimista", "triste", "filosofico"] },
  { word: "deseja", themes: ["romantico", "sonho", "intimista"] },
  { word: "sonha", themes: ["sonho", "noite", "esperanca"] },
  { word: "imagina", themes: ["sonho", "criatividade", "intimista"] },
  { word: "cria", themes: ["vida", "arte", "esperanca"] },
  { word: "destrói", themes: ["triste", "intenso", "tempo"] },
  { word: "constrói", themes: ["esperanca", "tempo", "vida"] },
  { word: "planta", themes: ["natureza", "esperanca", "tempo"] },
  { word: "colhe", themes: ["natureza", "tempo", "recompensa"] },
  { word: "semeia", themes: ["natureza", "esperanca", "futuro"] },
  { word: "espera", themes: ["tempo", "romantico", "paciência"] },
  { word: "confia", themes: ["intimista", "esperanca", "leve"] },
  { word: "duvida", themes: ["intimista", "tempo", "filosofico"] },
  { word: "sabe", themes: ["sabedoria", "intimista", "verdade"] },
  { word: "ignora", themes: ["triste", "intimista", "negligência"] },
  { word: "pergunta", themes: ["intimista", "filosofico", "curiosidade"] },
  { word: "responde", themes: ["intimista", "encontro", "verdade"] },
  { word: "calcula", themes: ["tempo", "razão", "filosofico"] },
  { word: "erra", themes: ["caminho", "aprendizado", "tempo"] },
  { word: "aprende", themes: ["tempo", "crescimento", "esperanca"] },
  { word: "ensina", themes: ["sabedoria", "tempo", "conexão"] },
  { word: "mostra", themes: ["claro", "revelação", "intimista"] },
  { word: "esconde", themes: ["mistério", "silencio", "intimista"] },
  { word: "revela", themes: ["verdade", "intimista", "claro"] },
  { word: "cobre", themes: ["proteção", "natureza", "intimista"] },
  { word: "descobre", themes: ["descoberta", "esperanca", "caminho"] },
  { word: "inventa", themes: ["criatividade", "sonho", "leve"] },
  { word: "recria", themes: ["renovação", "arte", "esperanca"] }
]

export const adjectives = [
  // originais
  { word: "silencioso", themes: ["silencio", "noite"] },
  { word: "suave", themes: ["leve", "romantico"] },
  { word: "leve", themes: ["natureza", "intimista"] },
  { word: "frio", themes: ["chuva", "triste"] },
  { word: "quente", themes: ["dia", "romantico"] },
  { word: "vazio", themes: ["solidao", "triste"] },
  { word: "calmo", themes: ["silencio", "natureza"] },
  { word: "lento", themes: ["tempo", "melancolico"] },
  { word: "rápido", themes: ["tempo"] },
  { word: "distante", themes: ["romantico", "melancolico"] },
  { word: "profundo", themes: ["intimista", "mar"] },
  { word: "escuro", themes: ["noite", "melancolico"] },
  { word: "claro", themes: ["dia", "esperanca"] },
  { word: "triste", themes: ["triste", "melancolico"] },
  { word: "doce", themes: ["romantico", "intimista"] },
  { word: "amargo", themes: ["triste"] },
  { word: "quieto", themes: ["silencio"] },
  { word: "solitário", themes: ["solidao", "triste"] },
  { word: "infinito", themes: ["filosofico"] },
  { word: "eterno", themes: ["tempo", "filosofico"] },
  { word: "breve", themes: ["tempo"] },
  { word: "antigo", themes: ["memoria"] },
  { word: "novo", themes: ["esperanca"] },
  { word: "delicado", themes: ["romantico", "leve"] },
  { word: "sujo", themes: ["chuva", "cotidiano"] },
  { word: "vivo", themes: ["esperanca"] },
  { word: "apagado", themes: ["melancolico"] },

  // novos – expandidos
  { word: "úmido", themes: ["chuva", "natureza", "intimista"] },
  { word: "seco", themes: ["natureza", "tempo", "triste"] },
  { word: "molhado", themes: ["chuva", "natureza", "leve"] },
  { word: "gelado", themes: ["frio", "silencio", "triste"] },
  { word: "quente", themes: ["calor", "aconchego", "paixao"] },
  { word: "macio", themes: ["leve", "aconchego", "intimista"] },
  { word: "áspero", themes: ["natureza", "tempo", "dureza"] },
  { word: "liso", themes: ["leve", "calma", "natureza"] },
  { word: "brilhante", themes: ["luz", "esperanca", "dia"] },
  { word: "opaco", themes: ["sombra", "melancolico", "silencio"] },
  { word: "transparente", themes: ["água", "verdade", "leve"] },
  { word: "turvo", themes: ["água", "mistério", "dúvida"] },
  { word: "colorido", themes: ["alegria", "natureza", "vida"] },
  { word: "cinzento", themes: ["nuvem", "triste", "dia"] },
  { word: "azul", themes: ["céu", "mar", "calma"] },
  { word: "verde", themes: ["natureza", "esperanca", "vida"] },
  { word: "vermelho", themes: ["paixao", "intenso", "fogo"] },
  { word: "dourado", themes: ["sol", "esperanca", "riqueza"] },
  { word: "prateado", themes: ["lua", "noite", "leve"] },
  { word: "alto", themes: ["céu", "montanha", "aspiração"] },
  { word: "baixo", themes: ["terra", "simples", "intimista"] },
  { word: "longe", themes: ["distancia", "melancolico", "romantico"] },
  { word: "perto", themes: ["intimista", "aconchego", "encontro"] },
  { word: "grande", themes: ["natureza", "filosofico", "infinito"] },
  { word: "pequeno", themes: ["intimista", "simples", "leve"] },
  { word: "fino", themes: ["leve", "delicado", "natureza"] },
  { word: "grosso", themes: ["natureza", "força", "simples"] },
  { word: "duro", themes: ["pedra", "tempo", "força"] },
  { word: "frágil", themes: ["leve", "delicado", "tempo"] },
  { word: "forte", themes: ["força", "natureza", "esperanca"] },
  { word: "veloz", themes: ["tempo", "movimento", "vento"] },
  { word: "devagar", themes: ["tempo", "calma", "melancolico"] },
  { word: "imprevisível", themes: ["natureza", "tempo", "mistério"] },
  { word: "constante", themes: ["tempo", "natureza", "calma"] },
  { word: "mutável", themes: ["tempo", "natureza", "filosofico"] },
  { word: "efêmero", themes: ["tempo", "instante", "leve"] },
  { word: "perpétuo", themes: ["tempo", "eterno", "filosofico"] },
  { word: "vasto", themes: ["mar", "céu", "infinito"] },
  { word: "íntimo", themes: ["intimista", "romantico", "pessoal"] },
  { word: "público", themes: ["cotidiano", "social", "movimento"] },
  { word: "comum", themes: ["cotidiano", "simples", "universal"] },
  { word: "raro", themes: ["especial", "instante", "valor"] },
  { word: "simples", themes: ["cotidiano", "leve", "verdade"] },
  { word: "complexo", themes: ["filosofico", "intimista", "mistério"] },
  { word: "puro", themes: ["natureza", "verdade", "leve"] },
  { word: "impuro", themes: ["mistura", "cotidiano", "triste"] },
  { word: "brando", themes: ["vento", "calma", "leve"] },
  { word: "violento", themes: ["tempestade", "intenso", "caos"] },
  { word: "manso", themes: ["animal", "calma", "natureza"] },
  { word: "selvagem", themes: ["natureza", "liberdade", "intenso"] },
  { word: "vago", themes: ["memoria", "sonho", "mistério"] },
  { word: "nítido", themes: ["memoria", "claro", "verdade"] },
  { word: "impreciso", themes: ["sonho", "memoria", "mistério"] },
  { word: "exato", themes: ["tempo", "verdade", "precisão"] },
  { word: "absurdo", themes: ["filosofico", "sonho", "caos"] },
  { word: "lógico", themes: ["razão", "ordem", "filosofico"] },
  { word: "poético", themes: ["arte", "intimista", "leve"] },
  { word: "prosaico", themes: ["cotidiano", "simples", "real"] },
  { word: "mágico", themes: ["sonho", "natureza", "mistério"] },
  { word: "real", themes: ["cotidiano", "verdade", "simples"] },
  { word: "imaginário", themes: ["sonho", "criatividade", "leve"] },
  { word: "sonhador", themes: ["sonho", "intimista", "leve"] },
  { word: "desperto", themes: ["dia", "consciência", "claro"] },
  { word: "adormecido", themes: ["noite", "sono", "calma"] },
  { word: "esquecido", themes: ["memoria", "tempo", "triste"] },
  { word: "lembrado", themes: ["memoria", "carinho", "tempo"] },
  { word: "perdido", themes: ["caminho", "tempo", "melancolico"] },
  { word: "achado", themes: ["descoberta", "esperanca", "encontro"] },
  { word: "abandonado", themes: ["solidao", "triste", "tempo"] },
  { word: "acolhedor", themes: ["aconchego", "intimista", "calor"] },
  { word: "hostil", themes: ["natureza", "triste", "intenso"] },
  { word: "amigável", themes: ["aconchego", "calor", "encontro"] },
  { word: "melancólico", themes: ["triste", "tempo", "intimista"] },
  { word: "alegre", themes: ["alegria", "leve", "dia"] },
  { word: "sereno", themes: ["calma", "silencio", "natureza"] },
  { word: "ansioso", themes: ["tempo", "espera", "intimista"] },
  { word: "paciente", themes: ["tempo", "calma", "esperanca"] },
  { word: "impaciente", themes: ["tempo", "movimento", "intenso"] },
  { word: "curioso", themes: ["descoberta", "intimista", "leve"] },
  { word: "indiferente", themes: ["triste", "distancia", "vazio"] },
  { word: "apaixonado", themes: ["romantico", "intenso", "paixao"] },
  { word: "desapaixonado", themes: ["triste", "vazio", "melancolico"] },
  { word: "confiante", themes: ["esperanca", "leve", "força"] },
  { word: "inseguro", themes: ["triste", "intimista", "medo"] },
  { word: "corajoso", themes: ["força", "esperanca", "desafio"] },
  { word: "medroso", themes: ["medo", "triste", "intimista"] }
]