export const phrases = [
    "Acredite que você pode, você já está no meio do caminho.",
    "O único limite para os seus sonhos é você mesmo.",
    "Não pare quando estiver cansado, pare quando tiver terminado.",
    "A persistência é o caminho do êxito.",
    "Seja mais forte do que a sua desculpa.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Levante, sacuda a poeira e dê a volta por cima.",
    "Você é mais forte do que imagina.",
    "Cada novo dia é uma chance de recomeçar.",
    "A dor é temporária, a desistência é para sempre.",
    "Acredite em si mesmo e tudo será possível.",
    "Você já tem tudo o que precisa para ser incrível.",
    "Não se compare com os outros, compare-se com quem você foi ontem.",
    "Você é único e isso é o seu superpoder.",
    "Confie no seu potencial.",
    "A sua única competição é você mesmo.",
    "Você pode mais do que imagina.",
    "Seja a sua maior inspiração.",
    "Valorize-se, ninguém pode fazer isso por você.",
    "Você merece conquistar tudo o que deseja.",
    "Não espere a oportunidade perfeita, crie a sua.",
    "O agora é a hora de agir.",
    "Comece onde está, use o que tem, faça o que puder.",
    "Coragem é medo que rezou e levantou pra lutar.",
    "Dê o primeiro passo, mesmo sem ver a escada inteira.",
    "O segredo é começar.",
    "A jornada de mil milhas começa com um único passo.",
    "Não deixe para amanhã o que você pode conquistar hoje.",
    "Arrisque-se, o não você já tem.",
    "A zona de conforto é inimiga da evolução.",
    "Depois da tempestade sempre vem a bonança.",
    "Mantenha o pensamento positivo, mesmo nos dias nublados.",
    "A felicidade está nas pequenas coisas.",
    "Acredite que coisas boas estão por vir.",
    "O sol nasce para todos, mas só quem acorda cedo vê.",
    "Gratidão transforma o que temos em suficiente.",
    "Cada dia é uma nova oportunidade para ser feliz.",
    "Otimismo é a fé que leva à realização.",
    "Sorria, você está sendo esculpido para o sucesso.",
    "A vida é 10% do que acontece e 90% de como você reage.",
    "O sucesso é a soma de pequenos esforços repetidos.",
    "O fracasso é apenas a oportunidade de começar de novo, com mais experiência.",
    "Não existe sucesso sem obstáculos.",
    "Quem quer fazer um jeito encontra, quem não quer uma desculpa arranja.",
    "A vitória é dos persistentes.",
    "O sucesso não é definitivo, o fracasso não é fatal: é a coragem de continuar que conta.",
    "Se você pode sonhar, pode realizar.",
    "Grandes conquistas exigem grandes riscos.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Faça hoje o que os outros não fazem, para ter amanhã o que os outros não têm.",
    "Foco, força e fé.",
    "Respira, confia, segue.",
    "Você é capaz.",
    "Agora vai!",
    "Não desista.",
    "Persista.",
    "Acredite.",
    "Conquiste.",
    "Realize.",
    "Voe."
]