# Generated by Django 6.0.1 on 2026-02-03 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_created_at_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aea996be-cdf5-44f3-9910-4956833a8a79'), editable=False, primary_key=True, serialize=False),
        ),
    ]
