version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: spfc_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: apitrescores
    ports:
      - "1992:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: