# Generated by Django 5.2.4 on 2025-07-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único baseado no título.', max_length=250, unique=True, verbose_name='slug'),
        ),
    ]
