# Generated by Django 5.2.6 on 2025-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
