# Generated by Django 5.2.6 on 2025-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studysession_date_alter_studysession_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='duration_study_session',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração do estudo no dia'),
        ),
    ]
