# Generated by Django 5.2.6 on 2025-09-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studysession_duration_study_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de dias do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_goal_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo de estudo em minutos'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration_study_session',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Duração do estudo no dia'),
        ),
    ]
