# Generated by Django 5.2.6 on 2025-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_days_alter_project_total_goal_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
