# Generated by Django 5.2.6 on 2025-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_studysession_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='description',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
