# Generated by Django 5.2.6 on 2025-09-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studysession_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='name',
        ),
        migrations.AlterField(
            model_name='studysession',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
