# Generated by Django 5.2.6 on 2025-09-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_studysession_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='important_date',
            field=models.BooleanField(default=False),
        ),
    ]
