# Generated by Django 5.2.6 on 2025-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studysession_important_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='landmark_to_register',
            field=models.BooleanField(default=False),
        ),
    ]
