word_list = [
    {'word': 'cama', 'tip': 'Tem no quarto'},
    {'word': 'geladeira', 'tip': 'Guarda comida'},
    {'word': 'cachorro', 'tip': 'Melhor amigo do homem'},
    {'word': 'gato', 'tip': 'Adora um colo'},
    {'word': 'banana', 'tip': 'Fruta amarela'},
    {'word': 'abacaxi', 'tip': 'Fruta com coroa'},
    {'word': 'carro', 'tip': 'Tem quatro rodas'},
    {'word': 'aviao', 'tip': 'Meio de transporte aéreo'},
    {'word': 'bicicleta', 'tip': 'Tem duas rodas'},
    {'word': 'praia', 'tip': 'Areia e mar'},
    {'word': 'igreja', 'tip': 'Lugar de oração'},
    {'word': 'mercado', 'tip': 'Lugar de compras'},
    {'word': 'computador', 'tip': 'Tem teclado e tela'},
    {'word': 'celular', 'tip': 'Todo mundo tem na mão'},
    {'word': 'telefone', 'tip': 'Já foi de disco'},
    {'word': 'professor', 'tip': 'Dá aulas'},
    {'word': 'medico', 'tip': 'Cuida da saúde'},
    {'word': 'bombeiro', 'tip': 'Apaga fogo'},
    {'word': 'policial', 'tip': 'Mantém a ordem'},
    {'word': 'engenheiro', 'tip': 'Constrói obras'},
    {'word': 'futebol', 'tip': 'Esporte mais popular do Brasil'},
    {'word': 'basquete', 'tip': 'Bola laranja e cesta'},
    {'word': 'natacao', 'tip': 'Esporte na água'},
    {'word': 'xadrez', 'tip': 'Jogo de tabuleiro com rei e rainha'},
    {'word': 'violao', 'tip': 'Instrumento de cordas'},
    {'word': 'piano', 'tip': 'Instrumento de teclas'},
    {'word': 'bateria', 'tip': 'Instrumento de percussão'},
    {'word': 'samba', 'tip': 'Ritmo brasileiro'},
    {'word': 'sertanejo', 'tip': 'Estilo musical do interior'},
    {'word': 'rock', 'tip': 'Estilo musical com guitarra'},
    {'word': 'hamburguer', 'tip': 'Comida de fast-food'},
    {'word': 'pizza', 'tip': 'Redonda e deliciosa'},
    {'word': 'feijoada', 'tip': 'Prato típico brasileiro'},
    {'word': 'sushi', 'tip': 'Comida japonesa'},
    {'word': 'churrasco', 'tip': 'Carne na brasa'},
    {'word': 'lasanha', 'tip': 'Prato italiano'},
    {'word': 'cafe', 'tip': 'Bebida que desperta'},
    {'word': 'cerveja', 'tip': 'Bebida feita de cevada'},
    {'word': 'agua', 'tip': 'Fonte da vida'},
    {'word': 'coca cola', 'tip': 'Refrigerante famoso'},
    {'word': 'Nike', 'tip': 'Marca de tênis'},
    {'word': 'Adidas', 'tip': 'Marca esportiva alemã'},
    {'word': 'Samsung', 'tip': 'Marca de eletrônicos'},
    {'word': 'Apple', 'tip': 'Marca de iPhone'},
    {'word': 'Microsoft', 'tip': 'Dona do Windows'},
    {'word': 'Google', 'tip': 'Ferramenta de busca'},
    {'word': 'YouTube', 'tip': 'Vídeos na internet'},
    {'word': 'Instagram', 'tip': 'Rede social de fotos'},
    {'word': 'Facebook', 'tip': 'Rede social famosa'},
    {'word': 'TikTok', 'tip': 'Rede social de vídeos curtos'},
    {'word': 'carteira', 'tip': 'Guarda dinheiro'},
    {'word': 'mochila', 'tip': 'Usa nas costas'},
    {'word': 'oculos', 'tip': 'Ajuda a enxergar'},
    {'word': 'relogio', 'tip': 'Marca as horas'},
    {'word': 'anel', 'tip': 'Usa no dedo'},
    {'word': 'sapato', 'tip': 'Vai nos pés'},
    {'word': 'camisa', 'tip': 'Roupa de cima'},
    {'word': 'calca', 'tip': 'Roupa de baixo'},
    {'word': 'chapeu', 'tip': 'Protege a cabeça'},
    {'word': 'copo', 'tip': 'Bebe líquido'},
    {'word': 'prato', 'tip': 'Serve comida'},
    {'word': 'garfo', 'tip': 'Talher com dentes'},
    {'word': 'faca', 'tip': 'Corta os alimentos'},
    {'word': 'colher', 'tip': 'Talher para sopa'},
    {'word': 'sofa', 'tip': 'Fica na sala'},
    {'word': 'televisao', 'tip': 'Tem canais'},
    {'word': 'controle', 'tip': 'Muda os canais'},
    {'word': 'janela', 'tip': 'Abre para o lado de fora'},
    {'word': 'porta', 'tip': 'Abre e fecha a entrada'},
    {'word': 'chave', 'tip': 'Abre fechaduras'},
    {'word': 'carteira', 'tip': 'Guarda documentos'},
    {'word': 'dinheiro', 'tip': 'Todo mundo quer'},
    {'word': 'viagem', 'tip': 'Aventura fora de casa'},
    {'word': 'hotel', 'tip': 'Hospedagem'},
    {'word': 'onibus', 'tip': 'Transporte coletivo'},
    {'word': 'metro', 'tip': 'Corre debaixo da terra'},
    {'word': 'navio', 'tip': 'Navega no mar'},
    {'word': 'planeta', 'tip': 'A Terra é um'},
    {'word': 'lua', 'tip': 'Aparece de noite'},
    {'word': 'estrela', 'tip': 'Brilha no céu'},
    {'word': 'sol', 'tip': 'Ilumina o dia'},
    {'word': 'galaxia', 'tip': 'A Via Láctea é uma'},
]
