version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gamer_deals_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: gamer_deals
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: